services:
  - type: web
    name: crucigrama-backend
    runtime: docker
    repo: https://https://github.com/m0nt4ld0/crucigrama-backend
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m"
